name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      - name: Build
        run: echo "Build"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/Mobnet App Setup 1.0.0.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}